export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';

export const TEACHERS_STATE_CHANGE = 'TEACHERS_STATE_CHANGE';

export const USER_ANNONCE_STATE_CHANGE = 'USER_ANNONCE_STATE_CHANGE';

export const CLEAR_DATA = 'CLEAR_DATA';
